//! Reverse golden file tests: Go-encoded → Rust-decoded.
//!
//! The canonical (forward) goldens in `testdata/golden/*.bin` are generated by
//! Rust and verified by Go. This file does the inverse — it reads
//! `testdata/golden/go_*.bin`, which are generated by Go
//! (`server/internal/protocol/golden_reverse_test.go::TestGenerateReverseGoldens`
//! under `GENERATE_GOLDEN=1`), and asserts that the Rust decoder accepts them
//! and produces the canonical struct values.
//!
//! Closes the long-standing "Golden File Tests Are One-Directional" tech-debt
//! entry. Together with the forward goldens, this guarantees byte-level wire
//! compatibility in both directions.

use mesh_protocol::*;
use std::path::PathBuf;

fn golden_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("OPENGATE_GOLDEN_DIR") {
        return PathBuf::from(dir);
    }
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../../../testdata/golden");
    path
}

/// Read a Go-generated golden file. The reverse fixtures are committed, so a
/// missing file is a test failure rather than a soft pass.
fn read_go_golden(name: &str) -> Vec<u8> {
    let path = golden_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {}", path.display(), e))
}

fn decode_frame(name: &str) -> Frame {
    let bytes = read_go_golden(name);
    let (frame, consumed) =
        Frame::decode(&bytes).unwrap_or_else(|e| panic!("Rust decoder rejected {}: {:?}", name, e));
    assert_eq!(
        consumed,
        bytes.len(),
        "Rust decoder did not consume the full frame for {}: consumed={}, len={}",
        name,
        consumed,
        bytes.len()
    );
    frame
}

const GOLDEN_SESSION_TOKEN: &str =
    "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";

#[test]
fn reverse_golden_ping() {
    let frame = decode_frame("go_ping.bin");
    assert!(matches!(frame, Frame::Ping));
}

#[test]
fn reverse_golden_pong() {
    let frame = decode_frame("go_pong.bin");
    assert!(matches!(frame, Frame::Pong));
}

#[test]
fn reverse_golden_heartbeat() {
    let frame = decode_frame("go_control_heartbeat.bin");
    match frame {
        Frame::Control(ControlMessage::AgentHeartbeat { timestamp }) => {
            assert_eq!(timestamp, 1_700_000_000);
        }
        other => panic!("expected AgentHeartbeat, got {:?}", other),
    }
}

#[test]
fn reverse_golden_agent_register() {
    let frame = decode_frame("go_control_agent_register.bin");
    match frame {
        Frame::Control(ControlMessage::AgentRegister {
            capabilities,
            hostname,
            os,
            arch,
            version,
        }) => {
            assert_eq!(capabilities.len(), 2);
            assert_eq!(capabilities[0], AgentCapability::RemoteDesktop);
            assert_eq!(capabilities[1], AgentCapability::Terminal);
            assert_eq!(hostname, "golden-test-host");
            assert_eq!(os, "linux");
            assert_eq!(arch, "amd64");
            assert_eq!(version, "0.1.0");
        }
        other => panic!("expected AgentRegister, got {:?}", other),
    }
}

#[test]
fn reverse_golden_session_request() {
    let frame = decode_frame("go_control_session_request.bin");
    match frame {
        Frame::Control(ControlMessage::SessionRequest {
            token,
            relay_url,
            permissions,
        }) => {
            assert_eq!(token.as_str(), GOLDEN_SESSION_TOKEN);
            assert_eq!(relay_url, "wss://relay.example.com/relay");
            assert!(permissions.desktop);
            assert!(permissions.terminal);
            assert!(permissions.file_read);
            assert!(!permissions.file_write);
            assert!(permissions.input);
        }
        other => panic!("expected SessionRequest, got {:?}", other),
    }
}

#[test]
fn reverse_golden_chat_message() {
    let frame = decode_frame("go_control_chat_message.bin");
    match frame {
        Frame::Control(ControlMessage::ChatMessage { text, sender }) => {
            assert_eq!(text, "hello from the operator");
            assert_eq!(sender, "operator@example.com");
        }
        other => panic!("expected ChatMessage, got {:?}", other),
    }
}

#[test]
fn reverse_golden_restart_agent() {
    let frame = decode_frame("go_control_restart_agent.bin");
    match frame {
        Frame::Control(ControlMessage::RestartAgent { reason }) => {
            assert_eq!(reason, "restart requested from web UI");
        }
        other => panic!("expected RestartAgent, got {:?}", other),
    }
}

#[test]
fn reverse_golden_request_health_window() {
    let frame = decode_frame("go_control_request_health_window.bin");
    match frame {
        Frame::Control(ControlMessage::RequestHealthWindow { since_ts, limit }) => {
            assert_eq!(since_ts, 1_700_000_000);
            assert_eq!(limit, 12);
        }
        other => panic!("expected RequestHealthWindow, got {:?}", other),
    }
}

#[test]
fn reverse_golden_unknown_future_server_to_agent() {
    let frame = decode_frame("go_control_unknown_future_server_to_agent.bin");
    assert!(matches!(frame, Frame::Control(ControlMessage::Unknown)));
}

#[test]
fn reverse_golden_desktop_frame() {
    let frame = decode_frame("go_desktop_frame.bin");
    match frame {
        Frame::Desktop(f) => {
            assert_eq!(f.sequence, 42);
            assert_eq!(f.x, 10);
            assert_eq!(f.y, 20);
            assert_eq!(f.width, 1920);
            assert_eq!(f.height, 1080);
            assert_eq!(f.encoding, FrameEncoding::Zstd);
            assert_eq!(f.data, vec![0xDE, 0xAD, 0xBE, 0xEF]);
        }
        other => panic!("expected Desktop, got {:?}", other),
    }
}
