#!/usr/bin/env bash
# sessionstart-install-git-hooks.sh — SessionStart hook. Installs git's native
# post-commit auto-push hook so "commit ⇒ push" works deterministically for BOTH
# foreground and BACKGROUNDED `git commit` tool calls (a Claude PostToolUse hook
# cannot — it does not fire after a backgrounded command completes).
#
# Idempotent and zero-manual-install: it rewrites a thin shim into the repo's git
# hooks dir every session, always pointing at the version-controlled logic in
# .claude/hooks/git-post-commit.sh. The shim is regenerated each session, so it
# always targets the current checkout path.
#
# Silent on success (no stdout) so it never pollutes the SessionStart context.
set -uo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$root" ] || exit 0

logic="$root/.claude/hooks/git-post-commit.sh"
[ -f "$logic" ] || exit 0
chmod +x "$logic" 2>/dev/null || true

# Resolve the effective hooks dir (respects worktrees / core.hooksPath); fall
# back to .git/hooks. Normalize a relative path against the work tree.
hooks_dir="$(git rev-parse --git-path hooks 2>/dev/null || echo ".git/hooks")"
case "$hooks_dir" in
  /*) : ;;
  *) hooks_dir="$root/$hooks_dir" ;;
esac
mkdir -p "$hooks_dir" 2>/dev/null || exit 0

target="$hooks_dir/post-commit"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  '# AUTO-GENERATED by .claude/hooks/sessionstart-install-git-hooks.sh — do not edit.' \
  '# Deterministic commit⇒push; logic lives in the version-controlled script below.' \
  "exec \"$logic\"" >"$target"
chmod +x "$target"
exit 0
