#!/usr/bin/env bash
# Installs git's native post-commit shim, which also fires after a backgrounded commit.
# It rewrites the shim each session to exec git-post-commit.sh and prints nothing on success.
set -uo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$root" ] || exit 0

logic="$root/.claude/hooks/git-post-commit.sh"
[ -f "$logic" ] || exit 0
chmod +x "$logic" 2>/dev/null || true

# The hooks dir honors worktrees and core.hooksPath, falling back to .git/hooks.
hooks_dir="$(git rev-parse --git-path hooks 2>/dev/null || echo ".git/hooks")"
case "$hooks_dir" in
  /*) : ;;
  *) hooks_dir="$root/$hooks_dir" ;;
esac
mkdir -p "$hooks_dir" 2>/dev/null || exit 0

target="$hooks_dir/post-commit"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  '# AUTO-GENERATED by .claude/hooks/sessionstart-install-git-hooks.sh — do not edit.' \
  '# Deterministic commit⇒push; logic lives in the version-controlled script below.' \
  "exec \"$logic\"" >"$target"
chmod +x "$target"
exit 0
