version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: /agent
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /web
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10
