extends: default

ignore:
  - deploy/terraform/cloud-init.yaml  # #cloud-config magic header must be line 1

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
