apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://opengate-victoriametrics:8428
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://opengate-loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: VictoriaMetrics
          matcherRegex: '"trace_id":"(\\w+)"'
          name: TraceID
          url: ""
