apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opengate.postgres.fullname" . }}-init
  labels:
    {{- include "opengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
data:
  init.sql: |
{{ .Files.Get "files/init.sql" | indent 4 }}
