apiVersion: v1
kind: Service
metadata:
  name: {{ include "opengate.fullname" . }}-server
  labels:
    {{- include "opengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "opengate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.httpPort }}
      targetPort: http
      protocol: TCP
