apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opengate.fullname" . }}-server-data
  labels:
    {{- include "opengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.server.dataVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.server.dataVolume.size }}
