#!/usr/bin/env bash
# Tests for scripts/check-comments: the rules end to end in every language, the
# hook, same-code and stats, then a sweep of this repository.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TYPESCRIPT="$REPO_ROOT/web/node_modules/typescript"

PASS=0
FAIL=0
FAILURES=()
TMP_DIR="$(mktemp -d)"
CHECKER="$TMP_DIR/check-comments"
trap 'rm -rf "$TMP_DIR"' EXIT

pass() {
  PASS=$((PASS + 1))
  printf '  ok   %s\n' "$1"
}
fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
  printf '  FAIL %s\n' "$1" >&2
}

shfmt_pin() {
  (
    # shellcheck source=../lib/tool-versions.sh
    . "$REPO_ROOT/scripts/lib/tool-versions.sh"
    printf '%s' "$TOOL_VERSION_SHFMT"
  )
}

put() {
  mkdir -p "$(dirname "$1")"
  cat >"$1"
}

write_base() {
  mkdir -p "$1/scripts/lib" "$1/scripts/check-comments"
  printf 'export TOOL_VERSION_SHFMT="%s"\n' "$(shfmt_pin)" >"$1/scripts/lib/tool-versions.sh"
  printf 'scripts/check-comments/scope.tsv\tthe scope list\n' >"$1/scripts/check-comments/scope.tsv"
}

write_clean() {
  local d="$1"
  put "$d/a.go" <<'EOF'
// Code generated by hand for the fixture. DO NOT EDIT.

// Package clean holds lookalikes that are not comments.
package clean

//go:generate echo "this directive line is long enough to pass one hundred characters without a width refusal"

// Greeting is the text sent once.
const Greeting = "// We follow ADR-1 and 2026-01-02 rather than this"

var raw = `/* We rather than ADR-1 */`

// Handler answers on localhost and https://example.com/path.
func Handler() string { return Greeting + raw } // Joins both values.

/*
Block holds one statement.
*/
var _ = Handler
EOF
  put "$d/b.rs" <<'EOF'
//! Clean lookalikes for the Rust lexer.

/// Holds one borrowed value.
pub struct Holder<'a> {
    value: &'a str,
}

pub fn quote() -> char {
    '"'
}

pub fn texts() -> (&'static str, &'static str, &'static [u8], &'static str, u8) {
    (r#"// We follow ADR-1"#, "/* rather than */", b"// We", r"# We", b'"')
}

/* Outer /* nested */ block holds two lines
   and closes once. */
pub fn escaped() -> char {
    '\''
}

pub fn label() {
    'outer: loop {
        break 'outer;
    }
}
EOF
  put "$d/c.ts" <<'EOF'
/// <reference types="vite/client" />
/**
 * Pattern matches doubled slashes.
 */
export const pattern = /\/\/ We follow ADR-1/;

export const template = `// We ${pattern.source} rather than`;

export const division = 4 / 2; // Halves the value.

// @ts-expect-error the fixture assigns a number to a string to prove the directive survives.
export const wrong: string = 1;
EOF
  put "$d/d.tsx" <<'EOF'
export function Card() {
  return (
    <p>
      // We follow ADR-1 rather than this
      {/* Shows the card body. */}
    </p>
  );
}
EOF
  put "$d/e.json" <<'EOF'
{
  "key": "// We follow ADR-1"
}
EOF
  put "$d/run.bash" <<'EOF'
#!/usr/bin/env bash
# shellcheck disable=SC2034
# Usage: run.bash NAME
#
# Environment:
#   NAME_PREFIX  (required) the prefix printed first.
#   NAME_SUFFIX  the suffix printed last.
#
# Exit codes:
#   0  printed
#   2  missing input
set -euo pipefail

unused="# We follow ADR-1"
echo "# rather than" # Prints the marker.
cat <<'DATA'
# We follow ADR-1 on 2026-01-02
DATA
echo "${#unused}"
EOF
  put "$d/config.yml" <<'EOF'
# Settings for the clean fixture.
key: "value # We follow ADR-1"
single: 'it''s # rather than'
plain: it's fine # Names the plain scalar.
script: |
  # We follow ADR-1
  echo hi
url: https://example.com/#anchor
EOF
  put "$d/.github/workflows/w.yml" <<'EOF'
name: w
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@0123456789abcdef0123456789abcdef01234567 # v4
      - name: Run
        run: |
          # Prints the greeting.
          echo "# We follow ADR-1"
          cat <<'DATA'
          # rather than 2026-01-02
          DATA
        shell: bash
      - uses: actions/github-script@0123456789abcdef0123456789abcdef01234567 # v7
        with:
          script: |
            // We follow ADR-1
EOF
  put "$d/deploy/helm/c/templates/_helpers.tpl" <<'EOF'
{{/* Names the chart. */}}
{{- define "c.name" -}}
{{- printf "%s # We follow ADR-1" .Chart.Name -}}
{{- end -}}
EOF
  put "$d/deploy/helm/c/templates/cm.yaml" <<'EOF'
{{- /* Renders the config map. */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c.name" . }} # Names the map.
data:
  script.sh: |
    # We follow ADR-1
    echo hi
EOF
  {
    printf '# Builds the fixture.\n.PHONY: build\nbuild:\n'
    printf '\t@echo "# We follow ADR-1"\n'
    printf "\t@echo 'rather than # ADR-1'\n"
  } >"$d/Makefile"
  put "$d/Dockerfile" <<'EOF'
# Builds the fixture image.
FROM alpine:3.20
# hadolint ignore=DL3018
RUN apk add --no-cache curl && echo "# We follow ADR-1"
EOF
  put "$d/x.toml" <<'EOF'
# Names the fixture package.
[package]
name = "clean # We follow ADR-1"
literal = 'rather than # ADR-1'
multi = """
# We follow ADR-1
"""
version = "1.0.0" # Starts the series.
EOF
  put "$d/main.tf" <<'EOF'
# Holds the fixture variable.
variable "name" {
  default = "clean # We follow ADR-1"
}

locals {
  script = <<-EOT
    # We follow ADR-1
  EOT
  other  = "// rather than" // Names the other value.
}

/* Closes the
   fixture. */
EOF
  put "$d/schema.sql" <<'EOF'
-- Creates the fixture table.
CREATE TABLE t (name text DEFAULT '-- We follow ADR-1');

CREATE FUNCTION f() RETURNS void AS $$
BEGIN
  -- We follow ADR-1 rather than
  RETURN;
END;
$$ LANGUAGE plpgsql;

/* Closes the fixture. */
EOF
  put "$d/policy.rego" <<'EOF'
package clean

# Allows the fixture.
allow if {
	input.name == "# We follow ADR-1"
	input.raw == `# rather than`
}
EOF
  put "$d/tool.py" <<'EOF'
#!/usr/bin/env python3
"""# We follow ADR-1 rather than this."""

# Prints one greeting.
print("# We follow ADR-1")  # Ends the line.
EOF
  put "$d/app.properties" <<'EOF'
# Names the fixture.
key=value # We follow ADR-1
list=a,\
  # rather than
EOF
  put "$d/.gitignore" <<'EOF'
# Ignores the build output.
/build/
EOF
  put "$d/style.css" <<'EOF'
/* Styles the fixture. */
.a::before {
  content: "/* We follow ADR-1 */";
}
EOF
  put "$d/index.html" <<'EOF'
<!doctype html>
<!-- Hosts the fixture. -->
<html><body><p>&lt;!-- We follow ADR-1 --&gt;</p><script>const a = "<!-- rather than -->";</script></body></html>
EOF
  put "$d/go.mod" <<'EOF'
// Names the fixture module.
module example.com/clean

go 1.22
EOF
}

write_violations() {
  local d="$1" wide
  wide="$(printf 'w%.0s' $(seq 1 100))"
  put "$d/length.go" <<'EOF'
package v

// One holds the first fact.
// Two holds the second fact.
// Three holds the third fact.
var A = 1
EOF
  printf 'package v\n\n// W is %s.\nvar W = 1\n' "$wide" >"$d/width.go"
  put "$d/refs.go" <<'EOF'
package v

// R follows ADR-123.
var R = 1

// S follows docs/plan.md for its shape.
var S = 1

// T bounds it per RFC 9000 §8.1.
var T = 1

// U sits in Phase B.
var U = 1

// V belongs to WS-19.
var V = 1

// X follows § 4.
var X = 1

// Y follows .claude/rules/code-comments.md for its shape.
var Y = 1
EOF
  put "$d/links.go" <<'EOF'
package v

const releases = "https://get.helm.sh/helm"

// L reads https://github.com/org/repo for its data.
var L = 1

// M landed in PR 12.
var M = 1

// N tracks #123 upstream.
var N = 1

// O failed in run 26929821908.
var O = 1

// P arrived in commit 2acbdbdc.
var P = 1

// Q downloads https://get.helm.sh/helm and answers on api.example.com.
var Q = 1
EOF
  put "$d/dates.go" <<'EOF'
package v

// D reads 2026-09-13.
var D = 1

// E fires at 2026-09-13T04:00:00Z.
var E = 1
EOF
  put "$d/words.go" <<'EOF'
package v

// H previously retried.
var H = 1

// I is not a cache.
var I = 1

// J holds the value rather than a copy.
var J = 1

// K is what we retry.
var K = 1

// ----
var Z = 1
EOF
  put "$d/v_test.go" <<'EOF'
package v

import "testing"

// TestA proves A.
func TestA(t *testing.T) {}

func BenchmarkB(b *testing.B) {} // Measures B.
EOF
  put "$d/lib.rs" <<'EOF'
/// Answers one.
pub fn one() -> u8 {
    1
}

#[cfg(test)]
mod tests {
    // Checks one.
    #[test]
    fn answers_one() {
        assert_eq!(super::one(), 1); // We expect one.
    }
}
EOF
  put "$d/a.test.ts" <<'EOF'
import { it } from 'vitest';

// Checks the sum.
it('adds', () => {});

describe.each([1])('with %i', () => {}); // Covers each.
EOF
  put "$d/page.tsx" <<'EOF'
export const Page = () => (
  <div>
    {/* We render the page. */}
  </div>
);
EOF
  put "$d/conf.json" <<'EOF'
{
  // Our key.
  "key": 1
}
EOF
  put "$d/run.bash" <<'EOF'
#!/usr/bin/env bash
# We print a greeting.
echo hi
EOF
  put "$d/env.bash" <<'EOF'
#!/usr/bin/env bash
# Environment:
#   A  the first.
#      continues here.
#      and again.
#      and more.
echo "${A:-}"
EOF
  put "$d/conf.yml" <<'EOF'
# See ADR-1.
key: 1
EOF
  put "$d/.github/workflows/w.yml" <<'EOF'
name: w
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # Previously ran twice.
          echo hi
EOF
  put "$d/deploy/helm/c/templates/cm.yaml" <<'EOF'
{{- /* Our map. */ -}}
apiVersion: v1
kind: ConfigMap
EOF
  put "$d/deploy/helm/c/templates/_helpers.tpl" <<'EOF'
{{/* We name the chart. */}}
{{- define "c.name" -}}c{{- end -}}
EOF
  printf '# We build it.\nbuild:\n\t@echo hi\n' >"$d/Makefile"
  put "$d/Dockerfile" <<'EOF'
# Our image.
FROM alpine:3.20
EOF
  put "$d/c.toml" <<'EOF'
key = 1 # Our key.
EOF
  put "$d/main.tf" <<'EOF'
// Our variable.
variable "a" {}
EOF
  put "$d/s.sql" <<'EOF'
-- Our table.
CREATE TABLE t (a int);
EOF
  put "$d/p.rego" <<'EOF'
package p

# Our rule.
allow := true
EOF
  put "$d/t.py" <<'EOF'
# Our tool.
print(1)
EOF
  put "$d/a.properties" <<'EOF'
# Our key.
key=1
EOF
  put "$d/.gitignore" <<'EOF'
# Our output.
/out/
EOF
  put "$d/s.css" <<'EOF'
/* Our style. */
.a {}
EOF
  put "$d/i.html" <<'EOF'
<!-- Our page. -->
<p>hi</p>
EOF
  put "$d/go.mod" <<'EOF'
// Our module.
module example.com/v
EOF
}

EXPECTED_VIOLATIONS="$(
  cat <<'EOF'
length.go:3: length
width.go:3: width
refs.go:3: doc-ref
refs.go:6: doc-ref
refs.go:12: doc-ref
refs.go:15: doc-ref
refs.go:18: doc-ref
links.go:5: link
links.go:8: link
links.go:11: link
links.go:14: link
links.go:17: link
dates.go:3: date
words.go:3: history
words.go:6: negation
words.go:9: negation
words.go:12: person
words.go:15: divider
v_test.go:5: test-doc
v_test.go:8: test-doc
lib.rs:8: test-doc
lib.rs:11: person
a.test.ts:3: test-doc
a.test.ts:6: test-doc
page.tsx:3: person
conf.json:2: person
run.bash:2: person
env.bash:2: length
conf.yml:1: doc-ref
.github/workflows/w.yml:8: history
deploy/helm/c/templates/cm.yaml:1: person
deploy/helm/c/templates/_helpers.tpl:1: person
Makefile:1: person
Dockerfile:1: person
c.toml:1: person
main.tf:1: person
s.sql:1: person
p.rego:3: person
t.py:1: person
a.properties:1: person
.gitignore:1: person
s.css:1: person
i.html:1: person
go.mod:1: person
EOF
)"

write_hook() {
  put "$1/existing.go" <<'EOF'
package hook

// We keep this one.
var B = 2
EOF
}

write_unknown() {
  printf 'notes\n' >"$1/notes.xyz"
  printf 'package u\n' >"$1/u.go"
}

write_stale() {
  printf 'vendor/**\tvendored code\n' >>"$1/scripts/check-comments/scope.tsv"
  printf 'package s\n' >"$1/s.go"
}

write_empty() {
  rm -f "$1/scripts/lib/tool-versions.sh"
  printf 'scripts/lib/tool-versions.sh\tthe manifest\n' >>"$1/scripts/check-comments/scope.tsv"
  printf 'export TOOL_VERSION_SHFMT="%s"\n' "$(shfmt_pin)" >"$1/scripts/lib/tool-versions.sh"
}

write_parse_error() {
  printf '#!/usr/bin/env bash\nif then fi (\n' >"$1/broken.bash"
}

make_fixture_repo() {
  local name="$1" dest="$TMP_DIR/repo-${2:-$1}"
  rm -rf "$dest"
  write_base "$dest"
  "write_$name" "$dest"
  git -C "$dest" init --quiet
  git -C "$dest" add -A
  printf '%s' "$dest"
}

run_checker() {
  local root="$1"
  shift
  OUTPUT=""
  STATUS=0
  OUTPUT="$("$CHECKER" --root "$root" --typescript "$TYPESCRIPT" "$@" 2>&1)" || STATUS=$?
}

expect_status() {
  local name="$1" want="$2"
  if [ "$STATUS" -eq "$want" ]; then
    pass "$name exits $want"
  else
    fail "$name exits $want (got $STATUS: $OUTPUT)"
  fi
}

expect_output() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" <<<"$OUTPUT"; then
    pass "$name reports $needle"
  else
    fail "$name reports $needle (got: $OUTPUT)"
  fi
}

expect_no_output() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" <<<"$OUTPUT"; then
    fail "$name does not report $needle (got: $OUTPUT)"
  else
    pass "$name does not report $needle"
  fi
}

echo "check-comments:"

if (cd "$REPO_ROOT" && GO111MODULE=off go build -o "$CHECKER" ./scripts/check-comments); then
  pass "checker builds without modules or network"
else
  fail "checker builds without modules or network"
  printf '\nSummary: %d passed, %d failed\n' "$PASS" "$FAIL"
  exit 1
fi

if (cd "$REPO_ROOT" && GO111MODULE=off go test -count=1 ./scripts/check-comments >"$TMP_DIR/unit.log" 2>&1); then
  pass "checker unit tests pass"
else
  fail "checker unit tests pass ($(tail -20 "$TMP_DIR/unit.log"))"
fi

if (cd "$REPO_ROOT" && GO111MODULE=off go test -count=1 ./scripts/check-doc-links >"$TMP_DIR/doc-links-unit.log" 2>&1); then
  pass "doc-link checker unit tests pass"
else
  fail "doc-link checker unit tests pass ($(tail -20 "$TMP_DIR/doc-links-unit.log"))"
fi

clean="$(make_fixture_repo clean)"
run_checker "$clean" sweep
expect_status "clean sweep" 0
expect_output "clean sweep" "check-comments: read "
expect_output "clean sweep" " 0 violations"
for lookalike in "We " "ADR-1" "2026-01-02" "rather than"; do
  expect_no_output "clean sweep" "$lookalike"
done

violations="$(make_fixture_repo violations)"
run_checker "$violations" sweep
expect_status "violations sweep" 1
while IFS= read -r expected; do
  [ -n "$expected" ] || continue
  expect_output "violations sweep" "$expected:"
done <<<"$EXPECTED_VIOLATIONS"
violation_count="$(grep -cE '^[^ ]+:[0-9]+: [a-z-]+: ' <<<"$OUTPUT" || true)"
expected_count="$(grep -c . <<<"$EXPECTED_VIOLATIONS")"
if [ "$violation_count" -eq "$expected_count" ]; then
  pass "violations sweep reports exactly the expected $expected_count violations"
else
  fail "violations sweep reports exactly the expected $expected_count violations (got $violation_count: $OUTPUT)"
fi

unknown="$(make_fixture_repo unknown)"
run_checker "$unknown" sweep
expect_status "unknown file type" 1
expect_output "unknown file type" "notes.xyz: unknown file type"

stale="$(make_fixture_repo stale)"
run_checker "$stale" sweep
expect_status "stale scope entry" 1
expect_output "stale scope entry" 'scope entry "vendor/**" matches no file'

empty="$(make_fixture_repo empty)"
run_checker "$empty" sweep
expect_status "empty sweep" 1
expect_output "empty sweep" "read no files"

unparsable="$(make_fixture_repo parse_error)"
run_checker "$unparsable" sweep
expect_status "shell shfmt rejects" 1
expect_output "shell shfmt rejects" "broken.bash:"
expect_output "shell shfmt rejects" ": parse: "

OUTPUT=""
STATUS=0
OUTPUT="$("$CHECKER" --root "$clean" --typescript "$TMP_DIR/missing" sweep 2>&1)" || STATUS=$?
expect_status "missing TypeScript compiler" 2
expect_output "missing TypeScript compiler" "npm ci"

drifted="$(make_fixture_repo clean drifted)"
printf 'export TOOL_VERSION_SHFMT="0.0.1"\n' >"$drifted/scripts/lib/tool-versions.sh"
run_checker "$drifted" sweep
expect_status "drifted shfmt" 2
expect_output "drifted shfmt" "shfmt"

hook_root="$(make_fixture_repo hook)"
hook_case() {
  local name="$1" envelope="$2" want="$3" needle="${4:-}"
  OUTPUT=""
  STATUS=0
  OUTPUT="$("$CHECKER" --root "$hook_root" --typescript "$TYPESCRIPT" hook <<<"$envelope" 2>&1)" || STATUS=$?
  expect_status "$name" "$want"
  if [ -n "$needle" ]; then
    expect_output "$name" "$needle"
  fi
}

hook_case "hook refuses a new doc reference" \
  '{"tool_name":"Write","tool_input":{"file_path":"new.go","content":"package p\n\n// Follows ADR-123.\nvar A = 1\n"}}' \
  1 "new.go:3: doc-ref"
hook_case "hook accepts a statement" \
  '{"tool_name":"Write","tool_input":{"file_path":"new.go","content":"package p\n\n// A counts retries.\nvar A = 1\n"}}' \
  0
hook_case "hook leaves an existing violation alone" \
  '{"tool_name":"Edit","tool_input":{"file_path":"existing.go","old_string":"var B = 2","new_string":"var B = 3"}}' \
  0
hook_case "hook refuses a second copy of an existing violation" \
  '{"tool_name":"Edit","tool_input":{"file_path":"existing.go","old_string":"var B = 2","new_string":"// We keep this one.\nvar B = 2"}}' \
  1 "person"
hook_case "hook applies MultiEdit in order with replace_all" \
  '{"tool_name":"MultiEdit","tool_input":{"file_path":"existing.go","edits":[{"old_string":"var B = 2","new_string":"var B = 2 // It is not a cache."},{"old_string":"It is not a cache.","new_string":"It holds one value.","replace_all":true}]}}' \
  0
hook_case "hook ignores a file outside the repository" \
  '{"tool_name":"Write","tool_input":{"file_path":"/outside-repo/x.go","content":"package p\n\n// ADR-1.\n"}}' \
  0
hook_case "hook ignores Markdown" \
  '{"tool_name":"Write","tool_input":{"file_path":"notes.md","content":"# ADR-1\n"}}' \
  0
hook_case "hook ignores other tools" \
  '{"tool_name":"Bash","tool_input":{"command":"true"}}' \
  0
hook_case "hook refuses a TypeScript test comment" \
  '{"tool_name":"Write","tool_input":{"file_path":"web/a.test.ts","content":"// checks it\nit(\"works\", () => {});\n"}}' \
  1 "test-doc"

same_root="$TMP_DIR/same-code"
write_base "$same_root"
printf 'package p\n\n// A holds one value, kept as a long comment.\n// It spans two lines.\nvar A = 1\n\nvar B = 2\n' >"$same_root/a.go"
printf '#!/usr/bin/env bash\n# Prints one greeting.\necho hi\n' >"$same_root/run.bash"
printf 'key: 1 # one\nother: 2\n' >"$same_root/c.yml"
git -C "$same_root" init --quiet
git -C "$same_root" add -A
git -C "$same_root" -c user.name=t -c user.email=t@example.com commit --quiet --no-verify -m base

printf 'package p\n\n// A holds one value.\nvar A = 1\n\nvar B = 2\n' >"$same_root/a.go"
printf '#!/usr/bin/env bash\necho hi\n' >"$same_root/run.bash"
printf 'key: 1\nother: 2\n' >"$same_root/c.yml"
run_checker "$same_root" same-code HEAD --no-new-comments
expect_status "same-code over comment-only edits" 0

printf 'package p\n\n// A holds one value.\nvar A = 1\n\n// B holds another.\nvar B = 2\n' >"$same_root/a.go"
run_checker "$same_root" same-code HEAD --no-new-comments
expect_status "same-code refuses a new comment" 1
expect_output "same-code refuses a new comment" "a.go:6: new comment"
run_checker "$same_root" same-code HEAD
expect_status "same-code without the comment check" 0

printf 'package p\n\n// A holds one value.\nvar A = 1\n\nvar B = 3\n' >"$same_root/a.go"
run_checker "$same_root" same-code HEAD
expect_status "same-code refuses a code change" 1
expect_output "same-code refuses a code change" "a.go: code differs"
printf 'a.go\n' >"$TMP_DIR/declared"
run_checker "$same_root" same-code HEAD --declared "$TMP_DIR/declared"
expect_status "same-code accepts a declared code change" 0

printf '#!/usr/bin/env bash\necho bye\n' >"$same_root/run.bash"
run_checker "$same_root" same-code HEAD --declared "$TMP_DIR/declared"
expect_status "same-code compares shell syntax trees" 1
expect_output "same-code compares shell syntax trees" "run.bash: code differs"

run_checker "$clean" stats
expect_status "stats" 0
expect_output "stats" "comment lines"
expect_output "stats" "language go:"
expect_output "stats" "area "

if python3 - "$REPO_ROOT/.claude/settings.json" <<'PY'; then
import json
import sys

with open(sys.argv[1], encoding="utf-8") as handle:
    settings = json.load(handle)

commands = [
    hook["command"]
    for group in settings["hooks"]["PreToolUse"]
    if group.get("matcher") == "Write|Edit|MultiEdit"
    for hook in group.get("hooks", [])
]
raise SystemExit(0 if ".claude/hooks/pretooluse-comment-check.sh" in commands else 1)
PY
  pass "settings register the comment hook"
else
  fail "settings register the comment hook"
fi

run_checker "$REPO_ROOT" sweep
if [ "$STATUS" -eq 0 ] && grep -qF " 0 violations" <<<"$OUTPUT"; then
  pass "repository sweep finds no violations ($(tail -1 <<<"$OUTPUT"))"
else
  tail -40 <<<"$OUTPUT" >&2
  fail "repository sweep finds no violations ($(tail -1 <<<"$OUTPUT"))"
fi

echo
echo "Summary: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
  printf '  - %s\n' "${FAILURES[@]}" >&2
  exit 1
fi
