#!/usr/bin/env bash
# Tests for the two overlay facts a load run depends on.
#
# The first is eviction order. Every pod on the single node is evictable, and
# nothing put production ahead of the rest — so a large fleet built on staging
# could take production's server or its database with it. A pod whose requests
# equal its limits is the last thing the kubelet reaches for, and that equality
# is what these tests hold.
#
# The second is an administrator that survives a cleanup. Every account in the
# staging database is created by a load run and removed by the next one, so the
# credential a run mints its enrollment token against cannot be one of them. The
# staging overlay seeds one that no run creates and no cleanup removes.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHART="$REPO_ROOT/deploy/helm/opengate"
PRODUCTION="$CHART/values-production.yaml"
STAGING="$CHART/values-staging.yaml"
BASE="$CHART/values.yaml"
JOB="$CHART/templates/loadtest-service-account-job.yaml"

PASS=0
FAIL=0
FAILURES=()
pass() {
  PASS=$((PASS + 1))
  printf '  ok   %s\n' "$1"
}
fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
  printf '  FAIL %s\n' "$1" >&2
}

echo "helm-overlays:"

# reads one dotted path out of a values file, or the empty string.
value_at() {
  python3 - "$1" "$2" <<'PY'
import sys

import yaml

path, dotted = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as handle:
    node = yaml.safe_load(handle) or {}
for part in dotted.split("."):
    if not isinstance(node, dict) or part not in node:
        print("")
        sys.exit(0)
    node = node[part]
print(node)
PY
}

# --- Production is last in the eviction order ---------------------------------

for component in server postgres; do
  req_cpu="$(value_at "$PRODUCTION" "$component.resources.requests.cpu")"
  lim_cpu="$(value_at "$PRODUCTION" "$component.resources.limits.cpu")"
  req_mem="$(value_at "$PRODUCTION" "$component.resources.requests.memory")"
  lim_mem="$(value_at "$PRODUCTION" "$component.resources.limits.memory")"

  if [ -n "$req_cpu" ] && [ "$req_cpu" = "$lim_cpu" ]; then
    pass "production $component asks for exactly the processor share it is capped at"
  else
    fail "production $component processor requests must equal limits (req=$req_cpu lim=$lim_cpu)"
  fi
  if [ -n "$req_mem" ] && [ "$req_mem" = "$lim_mem" ]; then
    pass "production $component asks for exactly the memory it is capped at"
  else
    fail "production $component memory requests must equal limits (req=$req_mem lim=$lim_mem)"
  fi
done

# The node allocates 1830m of processor and 1180m of it was already spoken for
# before this change. Production's pair may not claim so much that the two
# generator pods a load run creates cannot be scheduled beside it.
prod_cpu_total="$(
  python3 - "$PRODUCTION" <<'PY'
import sys

import yaml

with open(sys.argv[1], encoding="utf-8") as handle:
    values = yaml.safe_load(handle) or {}
total = 0
for component in ("server", "postgres"):
    raw = str(values.get(component, {}).get("resources", {}).get("requests", {}).get("cpu", "0"))
    total += int(raw[:-1]) if raw.endswith("m") else int(float(raw) * 1000)
print(total)
PY
)"
if [ "$prod_cpu_total" -gt 0 ] && [ "$prod_cpu_total" -le 600 ]; then
  pass "production's guaranteed share leaves the node room for a run's generators"
else
  fail "production server+postgres must request 1..600m in total (got ${prod_cpu_total}m)"
fi

# --- An administrator a cleanup does not remove -------------------------------

if [ -f "$JOB" ]; then
  pass "the chart carries the load-test service-account job"
else
  fail "expected $JOB"
fi

if [ -f "$JOB" ] && grep -qE '"?helm\.sh/hook"?:[[:space:]]*post-install,post-upgrade' "$JOB"; then
  pass "the account is seeded by the deployment, on install and on every upgrade"
else
  fail "the job must be a post-install,post-upgrade hook"
fi

# The account signs in, so it has a password — and that password is generated by
# the chart into a secret, never written into a file. A literal here would be a
# standing credential in a public repository.
SECRET="$CHART/templates/loadtest-service-account-secret.yaml"
if [ -f "$SECRET" ] && grep -q 'randAlphaNum' "$SECRET" && grep -q 'lookup "v1" "Secret"' "$SECRET"; then
  pass "the password is generated once and read back on every upgrade"
else
  fail "the password must be generated by the chart and preserved across upgrades"
fi

if [ -f "$JOB" ] && grep -q "gen_salt('bf', 10)" "$JOB"; then
  pass "the stored hash is one the server's own comparison accepts"
else
  fail "the seeded account's hash must be bcrypt at the cost the server uses"
fi

# The plaintext must reach the database without passing through a command line
# other processes in the pod could read.
if [ -f "$JOB" ] && ! grep -qE -- "-v[[:space:]]+(account_)?password=" "$JOB"; then
  pass "the password never appears on a command line"
else
  fail "the password must not be passed as a psql command-line variable"
fi

enabled_staging="$(value_at "$STAGING" "loadTest.serviceAccount.enabled")"
enabled_base="$(value_at "$BASE" "loadTest.serviceAccount.enabled")"
enabled_production="$(value_at "$PRODUCTION" "loadTest.serviceAccount.enabled")"

if [ "$enabled_staging" = "True" ]; then
  pass "staging seeds the load-test service account"
else
  fail "staging must set loadTest.serviceAccount.enabled: true (got '$enabled_staging')"
fi
if [ "$enabled_base" = "False" ]; then
  pass "the chart's default leaves the account unseeded"
else
  fail "values.yaml must default loadTest.serviceAccount.enabled to false (got '$enabled_base')"
fi
if [ "$enabled_production" = "" ] || [ "$enabled_production" = "False" ]; then
  pass "production does not seed a load-test account"
else
  fail "production must not enable the load-test service account"
fi

# The cleanup selects on a marker; the service account must fall outside it, or
# the run removes the credential it needs the next night.
account_email="$(value_at "$BASE" "loadTest.serviceAccount.email")"
if [ -n "$account_email" ] && [[ "$account_email" != *"opengate-loadtest"* ]] \
  && [[ "$account_email" != *"@test.local" ]]; then
  pass "the service account's address is outside every pattern cleanup selects on"
else
  fail "the service account address must not match a cleanup pattern (got '$account_email')"
fi

CLEANUP="$REPO_ROOT/scripts/loadtest-cleanup.sh"
if grep -q 'LOADTEST_SERVICE_ACCOUNT' "$CLEANUP"; then
  pass "cleanup knows which account it must never remove"
else
  fail "loadtest-cleanup.sh must exempt the service account"
fi

echo
echo "Summary: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
  printf '  - %s\n' "${FAILURES[@]}" >&2
  exit 1
fi
exit 0
