#!/usr/bin/env bash
# The exclusion list comes from a fixture properties file and the rename and copy set
# from SCEG_COPIES_OVERRIDE.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GUARD="$SCRIPT_DIR/../sonar-coverage-exclusion-guard.sh"
[ -f "$GUARD" ] || {
  echo "FAIL: $GUARD not found" >&2
  exit 1
}

PASS=0
FAIL=0
FAILURES=()
pass() {
  PASS=$((PASS + 1))
  printf '  ok   %s\n' "$1"
}
fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
  printf '  FAIL %s\n' "$1" >&2
}
assert_rc() {
  local name="$1" want="$2"
  shift 2
  "$@" >/dev/null 2>&1
  local got=$?
  if [ "$got" = "$want" ]; then pass "$name"; else fail "$name (want rc=$want got=$got)"; fi
}

FIXTURE="$(mktemp -d)"
trap 'rm -rf "$FIXTURE"' EXIT
mkdir -p "$FIXTURE/server/internal/agentapi" "$FIXTURE/web/src/types"
touch "$FIXTURE/server/internal/agentapi/server.go" \
  "$FIXTURE/server/internal/agentapi/server_connection.go" \
  "$FIXTURE/server/internal/agentapi/conn.go" \
  "$FIXTURE/web/src/types/api.d.ts"

write_props() {
  cat >"$FIXTURE/sonar-project.properties" <<PROPS
sonar.sources=server/internal
# JUSTIFICATIONS (the guard requires one line here per entry below):
#   **/types/** — generated type declarations
#   server/internal/agentapi/server.go — QUIC accept path, needs a live listener${2-}
sonar.coverage.exclusions=**/types/**,\\
  server/internal/agentapi/server.go${1-}
sonar.qualitygate.wait=true
PROPS
}
write_props

write_ignore_lists() {
  mkdir -p "$FIXTURE/.github/workflows" "$FIXTURE/scripts"
  cat >"$FIXTURE/.github/workflows/ci.yml" <<CI
          cargo llvm-cov nextest --ignore-filename-regex '(/tests/)' \\
          grep -v -E '/testutil/|api/openapi_gen\.go' coverage.out > coverage-prod.out
CI
  cat >"$FIXTURE/scripts/precommit-gauntlet.sh" <<GAUNTLET
  grep -v -E "${1:-/testutil/|api/openapi_gen\.go}" coverage.out > coverage-prod.out
    --ignore-filename-regex "${2:-(/tests/)}"
GAUNTLET
  cat >"$FIXTURE/Makefile" <<MAKEFILE
sonar-coverage:
	cd agent && cargo llvm-cov nextest --workspace --lcov --output-path lcov.info \\
		--ignore-filename-regex '${3:-(/tests/)}'
MAKEFILE
}
write_ignore_lists

run_guard() {
  SCEG_PROPERTIES="$FIXTURE/sonar-project.properties" \
    SCEG_ROOT="$FIXTURE" \
    SCEG_COPIES_OVERRIDE="${1-}" \
    bash "$GUARD"
}

echo "sonar-coverage-exclusion-guard"

assert_rc "no renames or copies at all passes" 0 run_guard ""

assert_rc "split of an excluded file into an unexcluded path fails" 1 \
  run_guard "server/internal/agentapi/server.go	server/internal/agentapi/conn.go"

write_props ",\\
  server/internal/agentapi/conn.go" "
#   server/internal/agentapi/conn.go — same QUIC accept path, split out of server.go"
assert_rc "split passes once the new path is excluded too" 0 \
  run_guard "server/internal/agentapi/server.go	server/internal/agentapi/conn.go"
write_props

assert_rc "split of a file that was never excluded is not the guard's business" 0 \
  run_guard "server/internal/agentapi/conn.go	server/internal/agentapi/server_connection.go"

assert_rc "a glob entry covers the split it matches" 0 \
  run_guard "web/src/types/api.d.ts	web/src/types/generated.d.ts"

rm "$FIXTURE/server/internal/agentapi/server.go"
assert_rc "an exclusion naming a file that is gone fails" 1 run_guard ""
touch "$FIXTURE/server/internal/agentapi/server.go"
assert_rc "and passes again once the path resolves" 0 run_guard ""

write_props ",\\
  server/internal/agentapi/conn.go"
assert_rc "an exclusion added without a justification fails" 1 run_guard ""
write_props

write_ignore_lists '/testutil/|/metrics/|api/openapi_gen\.go'
assert_rc "a Go ignore list that drifted from CI fails" 1 run_guard ""
write_ignore_lists '' '(main\.rs|/tests/)'
assert_rc "a Rust ignore list that drifted from CI fails" 1 run_guard ""

# The report SonarCloud reads is generated by a third command, whose list is compared too.
write_ignore_lists '' '' '(main\.rs|/webrtc\.rs|/tests/)'
assert_rc "a Rust ignore list that drifted in the Sonar report fails" 1 run_guard ""

write_ignore_lists
assert_rc "and passes once all three match again" 0 run_guard ""

assert_rc "a missing properties file is a prerequisite failure" 2 \
  env SCEG_PROPERTIES="$FIXTURE/absent.properties" SCEG_ROOT="$FIXTURE" \
  SCEG_COPIES_OVERRIDE="" bash "$GUARD"

REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
assert_rc "the repository's own exclusion list resolves" 0 \
  env SCEG_PROPERTIES="$REPO_ROOT/sonar-project.properties" SCEG_ROOT="$REPO_ROOT" \
  SCEG_COPIES_OVERRIDE="" bash "$GUARD"

echo
if [ "$FAIL" -ne 0 ]; then
  printf '%d passed, %d FAILED\n' "$PASS" "$FAIL" >&2
  for f in "${FAILURES[@]}"; do printf '  - %s\n' "$f" >&2; done
  exit 1
fi
printf '%d passed\n' "$PASS"
